import type { Metadata } from "next";
import "@/styles/app.css";


export const metadata: Metadata = {
  title: "To-do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
